workspace(name = "examples")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

########################
# MYPY SUPPORT
########################

local_repository(
    name = "mypy_integration",
    path = "../",
)

load("@mypy_integration//repositories:repositories.bzl", mypy_integration_repositories = "repositories")

mypy_integration_repositories()

load("@mypy_integration//repositories:deps.bzl", mypy_integration_deps = "deps")

mypy_integration_deps("//tools/typing:mypy_requirements.txt")

load("@mypy_integration_pip_deps//:requirements.bzl", install_mypy_deps = "install_deps")

install_mypy_deps()

load("@mypy_integration//:config.bzl", "mypy_configuration")

mypy_configuration("//tools/typing:mypy.ini")

########################
# PYTHON SUPPORT
########################
rules_python_version = "5c948dcfd4ca79c2ed3a87636c46abba9f5836e9"

http_archive(
    name = "rules_python",
    sha256 = "76e817a5e540f4c8a8b5e1de1e7afee6dfa42d78112a3694244450287ac20ebb",
    strip_prefix = "rules_python-{version}".format(version = rules_python_version),
    url = "https://github.com/bazelbuild/rules_python/archive/{version}.tar.gz".format(version = rules_python_version),
)

load("@rules_python//python:repositories.bzl", "py_repositories")

py_repositories()

load("@rules_python//python:pip.bzl", "pip_parse")

pip_parse(
    name = "my_deps",
    python_interpreter = "python3",
    requirements = "//third_party:requirements.txt",
)

load("@my_deps//:requirements.bzl", install_my_deps = "install_deps")

install_my_deps()

########################
# OTHER
########################

http_archive(
    name = "bazel_skylib",
    sha256 = "97e70364e9249702246c0e9444bccdc4b847bed1eb03c5a3ece4f83dfe6abc44",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.0.2/bazel-skylib-1.0.2.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.2/bazel-skylib-1.0.2.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

http_archive(
    name = "linting_system",
    sha256 = "8da0fedcfd5ebad2ff204caf62abfe5304f32280542128cccc044f56f0d7138d",
    strip_prefix = "bazel-linting-system-0.2.1",
    url = "https://github.com/thundergolfer/bazel-linting-system/archive/v0.2.1.zip",
)
